services:
  web:
    build: .
    ports:
      - "127.0.0.1:5000:5000"
    volumes:
      - ./db:/app/db
    environment:
      - FLASK_ENV=development
      - SECRET_KEY=ISW1013-UTN-sqli-lab-clave-segura-2026
      - FLASK_DEBUG=false
